### ISSUE TITLE
"wasm vector out of bounds" when running hello-driver example on Centos 7

### ISSUE THREAD

**Issue by ghost** [EOSIO/eos-vm#132]
I've built eos-vm on Centos 7.7, gcc 7.4 compiler.
When running tools/hello-driver I'm getting exception:
terminate called after throwing an instance of 'eosio::vm::wasm_vector_oob_exception'
  what():  wasm vector out of bounds

Here is a stack:
#0  0x00007f6ff7548337 in raise () from /lib64/libc.so.6
#1  0x00007f6ff7549a28 in abort () from /lib64/libc.so.6
#2  0x00007f6ff7e8a135 in __gnu_cxx::__verbose_terminate_handler () at ../../.././libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007f6ff7e87f26 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../.././libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007f6ff7e87f71 in std::terminate () at ../../.././libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007f6ff7e881b3 in __cxxabiv1::__cxa_throw (obj=<optimized out>, 
    tinfo=0x4f2870 <typeinfo for eosio::vm::wasm_vector_oob_exception>, 
    dest=0x41410a <eosio::vm::wasm_vector_oob_exception::~wasm_vector_oob_exception()>)
    at ../../.././libstdc++-v3/libsupc++/eh_throw.cc:93
#6  0x0000000000414473 in eosio::vm::detail::vector<unsigned int, eosio::vm::growable_allocator>::at (this=0x7ffe2be97098, i=0)
    at /home/alr/eos-vm/include/eosio/vm/vector.hpp:58
#7  0x000000000040d5b1 in eosio::vm::detail::vector<unsigned int, eosio::vm::growable_allocator>::operator[] (this=0x7ffe2be97098, 
    i=0) at /home/alr/eos-vm/include/eosio/vm/vector.hpp:76
#8  0x00000000004173c3 in eosio::vm::registered_host_functions<example_host_methods>::resolve<eosio::vm::module> (mod=...)
    at /home/alr/eos-vm/include/eosio/vm/host_function.hpp:575
#9  0x0000000000412312 in eosio::vm::backend<example_host_methods, eosio::vm::interpreter>::backend<eosio::vm::registered_host_functions<example_host_methods> > (this=0x7ffe2be96f10, code=...) at /home/alr/eos-vm/include/eosio/vm/backend.hpp:48
#10 0x0000000000403c47 in main (argc=4, argv=0x7ffe2be974a8) at /home/alr/eos-vm/tools/hello_driver.cpp:66

**Comment by jnordberg** [comment]
I have the exact same problem on macOS 10.15.1

```
Apple clang version 11.0.0 (clang-1100.0.33.12)
```

**Comment by jnordberg** [comment]
All tests are passing
