### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by lucas7788** [EOSIO/eos-vm#16]
hello, how to solve this question?
<img width="1377" alt="图片" src="https://user-images.githubusercontent.com/13885466/59279236-28dbfe80-8c96-11e9-8425-69494cee4c89.png">

**Comment by tbfleming** [comment]
`filesystem` is a standard C++ header. It means you have an old compiler.

**Comment by lucas7788** [comment]
@tbfleming   my gcc 是gcc (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
clang version 8.0.0 (tags/RELEASE_800/final)
g++ (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0

**Comment by tbfleming** [comment]
Yep. Too old.

**Comment by tbfleming** [comment]
gcc 9.1 is the first version which supports filesystem without special flags. In most installs, clang uses gcc's headers, so it's the gcc install which matters most.

**Comment by lucas7788** [comment]
@tbfleming  I upgrade my gcc to gcc9.1,  but I met another question.
<img width="1317" alt="图片" src="https://user-images.githubusercontent.com/13885466/59562676-1da41c80-9062-11e9-99ce-675c34c5448d.png">

**Comment by tbfleming** [comment]
killed can mean it out of memory

**Comment by larryk85** [comment]
Hey lucas7788, I went ahead and removed the filesystem stuff for now.  Please let us know if you still have issues.

**Comment by lucas7788** [comment]
@larryk85   I increase memory limit and it work, thank you

**Comment by johndebord** [comment]
@lucas7788 Try restarting your computer (freeing up every last bit of swap space), and try compiling with `make -j1`. Depending on how much RAM/swap-space you have, that might work.

<hr>

I just tested it on my system and here are my memory metrics:
```
i@debord:~$ free -th
              total        used        free      shared  buff/cache   available
Mem:           3.7G        1.5G        1.5G        127M        742M        1.9G
Swap:          1.3G        698M        661M
Total:         5.0G        2.1G        2.1G
```
