### ISSUE TITLE
make failed in Mac Xcode 10.2.1

### ISSUE THREAD

**Issue by xiaoyu1998** [EOSIO/eos-vm#29]
![屏幕快照 2019-06-29 下午7 33 59](https://user-images.githubusercontent.com/39975400/60383574-1559d180-9aa5-11e9-9325-f85448a2c44f.png)
![屏幕快照 2019-06-29 下午7 34 22](https://user-images.githubusercontent.com/39975400/60383576-1a1e8580-9aa5-11e9-892f-0d09a2fced4d.png)

**Comment by tbfleming** [comment]
xcode is based on clang 6, which is too old. Clang 8 works on macos.

**Comment by swatanabe-b1** [comment]
This is addressed by #31

**Comment by z497688734** [comment]
use  Clang 8  can work
