### ISSUE TITLE
variant.hpp:111:25: error: "invoke() is not a member of 'std'"

### ISSUE THREAD

**Issue by serghd** [EOSIO/eos-vm#57]
The error appears in building process, gcc-7 (7.4.0).
I can't add additional branch for pull request, so just add:
`
#include <functional>
`

in
eos-vm/include/eosio/vm/variant.hpp
for fixing it.

**Comment by swatanabe-b1** [comment]
This was fixed along with a few other similar issues that gcc 8.3 caught in 3daaaf5482347d3f8e822c090d997d204b5b97df.
